### ISSUE TITLE
Revert of dispatcher-related changes

### ISSUE THREAD

**Issue by Altai-man** [jonathanstowe/Lumberjack#1]
Hi! Sorry to bother you with this again, but as dispatcher related work is currently in the process of revert before the next rakudo release (to be replaced by a more robust mechanism), https://github.com/jonathanstowe/Lumberjack/commit/0173711f95bb47d43a9f0968db73ff741d524946 should be reverted to work on both 2020.02.1 and (hopefully) 2020.05.

**Comment by jonathanstowe** [comment]
Hi, I'm a bit confused, that change related to the change of the frames emitted by `Backtrace.new` omitting those in `Backtrace` itself.  I only changed some lines that just happened to have the word `dispatcher` in (unrelated to the rakudo dispatcher itself.)

**Comment by Altai-man** [comment]
Sorry for the confusion.

1)After 2020.02, we did some changes to Backtrace, resulting in the commit I linked to adapt to them.
2)Now, we are reverting them before doing a next release due to Circumstances.
So to continue to work properly on stable releases, I am suggesting to undo the part of changes which was broken on master for some time.

To test out your changes, you can use rakudo's https://github.com/rakudo/rakudo/pull/3651 branch, though it should behave just as 2020.02 did.
